# Generated by Django 2.1.5 on 2019-01-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=60, verbose_name='Nome Completo')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('endereco_cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('endereco_logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('endereco_numero', models.CharField(max_length=20, verbose_name='Numero')),
                ('endereco_bairro', models.CharField(max_length=60, verbose_name='Bairro')),
                ('endereco_cidade', models.CharField(max_length=60, verbose_name='Cidade')),
                ('endereco_estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('endereco_celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('endereco_telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco_email', models.CharField(max_length=254, verbose_name='E-mail')),
                ('endereco_email_confirmacao', models.CharField(max_length=254, verbose_name='Confirmação de e-mail')),
            ],
        ),
    ]
